#!/bin/bash

export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
	curl -s https://getcomposer.org/instal... | php -- --install-dir=$OPENSHIFT_DATA_DIR
fi

unset GIT_DIR
cd $OPENSHIFT_REPO_DIR
/usr/local/zend/bin/php $OPENSHIFT_DATA_DIR/composer.phar install
